spring.application.name=MYFIRSTPROJECT
spring.data.mongodb.host=localhost:
spring.data.mongodb.port=27017
spring.data.mongodb.database=JournalDb
#spring.data.mongodb.username=myUser
#pring.data.mongodb.password=myPassword we have commented out username and password because we are using local mongodb and it does not require authentication. If you are using a remote mongodb then you need to provide username and password.